# E4 C2 Backend gitlab ci file
# Currently we build using docker in a mirror of docker/Dockerfile.c2 
# It may be worth building that image, instead. 

# TODO: docker-in-docker

image: golang:1.11
stages:
  - build
  - test

before_script:
  - go get golang.org/x/tools/cmd/goimports
  - go install golang.org/x/tools/cmd/goimports
  - mkdir -p /go/src/teserakt/e4/c2backend
  - ln -s /builds/Teserakt/c2backend/  /go/src/teserakt/e4/c2backend
  - cd /go/src/teserakt/e4/c2backend/

build:
  stage: build
  only:
    - develop
    - master
  script:
    - ./scripts/build.sh

test:
  stage: test
  only:
    - develop
    - master
  script:
    - ./scripts/unittests.sh
