# E4 C2 Backend gitlab ci file
# Currently we build using docker in a mirror of docker/Dockerfile.c2 
# It may be worth building that image, instead. 

# TODO: docker-in-docker


stages:
  - build
  - test

build:base:
  image: golang:1.11
  stage: build
  only:
    - develop
    - master
  before_script:
    - go get golang.org/x/tools/cmd/goimports
    - go install golang.org/x/tools/cmd/goimports
    - mkdir -p /go/src/teserakt/e4/c2
    - ln -s /builds/Teserakt/c2/  /go/src/teserakt/e4/c2
    - cd /go/src/teserakt/e4/c2/
  script:
    - ./scripts/build.sh

# docker-in-docker build
build:docker:
  image: docker:stable
  script:
    - ./scripts/docker.sh

test:base:
  image: golang:1.11
  stage: test
  only:
    - develop
    - master
  script:
    - ./scripts/unittests.sh
