# E4 C2 Backend gitlab ci file
# Currently we build using docker in a mirror of docker/Dockerfile.c2 
# It may be worth building that image, instead. 

# TODO: need to see if we can get this script to produce docker images as well.


stages:
  - build
  - test

build:base:
  image: golang:1.12
  stage: build
  only:
    - develop
    - master
  before_script:
    - go get golang.org/x/tools/cmd/goimports
    - go install golang.org/x/tools/cmd/goimports
  script:
    - ./scripts/build.sh

# docker-in-docker build
#build:docker:
#  image: docker:stable
# script:
#    - ./scripts/docker.sh

test:base:
  image: golang:1.12
  stage: test
  only:
    - develop
    - master
  script:
    - ./scripts/unittests.sh
    - ./scripts/test.sh
