# E4 C2 Backend gitlab ci file
# Currently we build using docker in a mirror of docker/Dockerfile.c2 
# It may be worth building that image, instead. 

# TODO: docker-in-docker

image: golang:1.11
stages:
  - build
  - test

before_script:
  - go get golang.org/x/tools/cmd/goimports
  - go install golang.org/x/tools/cmd/goimports
  - go get github.com/golang/dep/cmd/dep
  - go install github.com/golang/dep/cmd/dep
  - mkdir -p /go/src/teserakt/e4go/
  - cp -r /builds/Teserakt/e4go/  /go/src/teserakt/e4go/
  - cd /go/src/teserakt/e4go/

build:
  stage: build
  only:
    - develop
    - master
  script:
    - dep ensure -v
    - ./scripts/build.sh

test:
  stage: test
  only:
    - develop
    - master
  script:
    - ./scripts/unittests.sh
