#mqtt-broker: tcp://localhost:1883
mqtt-broker: tcp://data.geo-satis.com:1884
mqtt-ID: e4c2
mqtt-username: usermqtt
mqtt-password: passmqtt

db-username: e4_c2_test
db-password: teserakte4

grpc-host-port: 0.0.0.0:5555

http-host-port: 0.0.0.0:8888


