receivers:
  opencensus:
    address: "127.0.0.1:55678"

exporters:
  jaeger:
    collector_endpoint: "http://localhost:14268/api/traces"

  prometheus:
    namespace: "teserakt"
    address: "localhost:9998"

zpages:
    port: 9999
