receivers:
  opencensus:
    address: "localhost:55678"

exporters:
  jaeger:
    collector_endpoint: "http://jaeger:14268/api/traces"

  prometheus:
    namespace: "teserakt"
    address: "0.0.0.0:9998"

zpages:
    port: 9999
