global:
  scrape_interval: 10s

  external_labels:
    monitor: 'teseraktagent'

scrape_configs:
  - job_name: 'teseraktagent'

    scrape_interval: 10s

    static_configs:
      - targets: ['oc-agent:9998']
